"""Add round_id to Summary model

Revision ID: 4b76cc0058a7
Revises: 786c1995045c
Create Date: 2025-02-26 12:06:28.573585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b76cc0058a7'
down_revision = '786c1995045c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_column('round_id')

    # ### end Alembic commands ###
