"""Add ai_summary field to Execution model

Revision ID: 786c1995045c
Revises: 10f83a867b64
Create Date: 2025-02-26 10:48:51.833410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786c1995045c'
down_revision = '10f83a867b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###
