"""Add current_round to Event model

Revision ID: c8c74e6ef55c
Revises: 4b76cc0058a7
Create Date: 2025-02-26 13:34:34.732210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c74e6ef55c'
down_revision = '4b76cc0058a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_round', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('current_round')

    # ### end Alembic commands ###
